#!/usr/bin/env zsh

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
git clone https://github.com/mrgnw/dotfiles ~/.zsh
ln -s ~/.zsh/.zshrc ~/.zshrc
sh -c "$(curl -fsSL https://git.io/zinit_install)"
